export const ko = {
  common: {
    save: "저장",
    cancel: "취소",
    delete: "삭제",
    edit: "수정",
    add: "추가",
    create: "생성",
    search: "검색",
    filter: "필터",
    loading: "로딩 중...",
    noData: "데이터가 없습니다",
    confirm: "확인",
    back: "뒤로",
    actions: "작업",
    status: "상태",
    date: "날짜",
    amount: "금액",
    description: "설명",
    name: "이름",
    email: "이메일",
    phone: "전화번호",
    address: "주소",
    notes: "메모",
    all: "전체",
    yes: "예",
    no: "아니오",
  },
  nav: {
    dashboard: "대시보드",
    clients: "고객 관리",
    projects: "프로젝트",
    invoices: "청구서",
    timeTracking: "시간 추적",
    finances: "수입/지출",
    settings: "설정",
    logout: "로그아웃",
  },
  auth: {
    login: "로그인",
    signup: "회원가입",
    email: "이메일",
    password: "비밀번호",
    confirmPassword: "비밀번호 확인",
    fullName: "이름",
    forgotPassword: "비밀번호를 잊으셨나요?",
    noAccount: "계정이 없으신가요?",
    hasAccount: "이미 계정이 있으신가요?",
    loginWithGoogle: "Google로 로그인",
    signupWithGoogle: "Google로 회원가입",
  },
  dashboard: {
    title: "대시보드",
    totalRevenue: "이번 달 수입",
    activeProjects: "진행 중 프로젝트",
    pendingInvoices: "미수금 청구서",
    hoursThisWeek: "이번 주 근무시간",
    recentProjects: "최근 프로젝트",
    upcomingDeadlines: "다가오는 마감일",
    pendingPayments: "미결제 청구서",
    monthlyRevenue: "월별 수입",
  },
  clients: {
    title: "고객 관리",
    newClient: "새 고객",
    companyName: "회사명",
    contactName: "담당자",
    businessNumber: "사업자등록번호",
    editClient: "고객 수정",
    deleteConfirm: "이 고객을 삭제하시겠습니까?",
    noClients: "등록된 고객이 없습니다",
  },
  projects: {
    title: "프로젝트",
    newProject: "새 프로젝트",
    projectName: "프로젝트명",
    client: "고객",
    startDate: "시작일",
    endDate: "종료일",
    budget: "예산",
    hourlyRate: "시급",
    editProject: "프로젝트 수정",
    tasks: "태스크",
    addTask: "태스크 추가",
    noProjects: "등록된 프로젝트가 없습니다",
  },
  invoices: {
    title: "청구서",
    newInvoice: "새 청구서",
    invoiceNumber: "청구서 번호",
    issueDate: "발행일",
    dueDate: "납부기한",
    subtotal: "소계",
    tax: "부가세 (10%)",
    total: "합계",
    items: "항목",
    addItem: "항목 추가",
    quantity: "수량",
    unitPrice: "단가",
    lineTotal: "금액",
    downloadPdf: "PDF 다운로드",
    markAsSent: "발송 처리",
    markAsPaid: "결제 완료",
    noInvoices: "등록된 청구서가 없습니다",
  },
  timeTracking: {
    title: "시간 추적",
    startTimer: "타이머 시작",
    stopTimer: "타이머 정지",
    addManual: "수동 입력",
    project: "프로젝트",
    duration: "소요시간",
    billable: "청구 가능",
    weeklySummary: "주간 요약",
    totalHours: "총 근무시간",
    noEntries: "기록된 시간이 없습니다",
  },
  finances: {
    title: "수입/지출",
    income: "수입",
    expense: "지출",
    netProfit: "순이익",
    addTransaction: "거래 추가",
    category: "카테고리",
    type: "유형",
    transactions: "거래 내역",
    monthlyOverview: "월별 개요",
    noTransactions: "등록된 거래가 없습니다",
  },
  settings: {
    title: "설정",
    profile: "프로필",
    businessInfo: "사업자 정보",
    businessName: "상호명",
    businessNumber: "사업자등록번호",
    bankName: "은행명",
    bankAccount: "계좌번호",
    defaultHourlyRate: "기본 시급",
    preferences: "환경설정",
    saved: "설정이 저장되었습니다",
  },
} as const
